version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'dependabot'
      - 'automerge'
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      linting:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'prettier*'
      typescript:
        patterns:
          - 'typescript'
          - '@typescript-eslint/*'
      minor-and-patch:
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'dependabot'
      - 'automerge'
    groups:
      github-actions:
        patterns:
          - '*'
