export const CAREERS = [
  {
    company: 'GovTech Edu Indonesia',
    link: 'https://www.govtechedu.id/',
    location: 'Jakarta, Indonesia',
    title: 'Software Development Engineer, Web',
    period: 'Jul 2023 - Dec 2024',
    long: '1 yrs 3 mos',
    summary:
      'Key contributor in a 3-person engineering team building an open data portal for the ministry of education from the ground along with the internal content management system to manage the data. Optimize the seo to gain 12K+ monthly organic traffic from search engines. Managing to get an external security penetration test from BSSN (National Cyber and Crypto Agency) with almost zero reported issues.',
    stacks: ['Next.js', 'React.js', 'GCP'],
    layout: 'right',
    promotion: false,
  },
  {
    company: 'Sayurbox',
    link: 'https://www.sayurbox.com/',
    location: 'Jakarta, Indonesia',
    title: 'Software Development Engineer III',
    period: 'Jul 2022 - May 2023',
    long: '11 months',
    summary:
      'Part of the engineering efficiency team to help engineers deliver the product more efficiently. Maintain the crash free rate from the main application up to 95%+. Unify the deployment strategy and look and feel for all internal tool services. Help the marketing team to increase the page coverage in the search engine to over 10K pages in a month.',
    stacks: ['React Native', 'React.js', 'GraphQL', 'AWS'],
    layout: 'left',
    promotion: false,
  },
  {
    company: 'Tokopedia',
    link: 'https://www.tokopedia.com/',
    location: 'Jakarta, Indonesia',
    title: 'Principal Engineer Web Platform',
    period: 'Jun 2019 - Jul 2022',
    long: '3 yrs 2 mos',
    summary:
      'Developed and maintained core tool kit for frontend engineers across company-wide. Led several tech migrations for 30+ frontend services such as from Datadog to Newrelic, from JS to TS, from Koa to Fastify, from Monorepo to Multi-repo, from Aliyun to GCP, etc. Championing web performance awareness and building in-house monitoring tools to collect daily performance scores including the one behind the auth. Writing technical documentations for the onboarding and interview process.',
    stacks: ['React.js', 'Svelte', 'GraphQL', 'GCP'],
    layout: 'right',
    promotion: false,
  },
  {
    company: 'Bizzy Indonesia',
    link: 'https://bizzy.co.id/',
    location: 'Jakarta, Indonesia',
    title: 'Software Architect Frontend',
    period: 'Feb 2019 - Jun 2019',
    long: '5 mos',
    summary:
      'Initiate the coding guidelines best practices using Nuxt.js & Vue.js. Maintain the shared libraries for frontend engineers while working in the transaction tribes to migrate the old features into serverless architecture on AWS. Reduce the bundle size to increase overall performance by splitting into 3 repo based on the domain. Setup static sites development for the marketing team.',
    stacks: ['Nuxt.js', 'Vue.js', 'AWS'],
    layout: 'left',
    promotion: false,
  },
  {
    company: 'Bizzy Indonesia',
    link: 'https://bizzy.co.id/',
    location: 'Jakarta, Indonesia',
    title: 'Software Development Engineer',
    period: 'Jul 2018 - Feb 2019',
    long: '7 mos',
    summary:
      'Initiate the coding guidelines best practices using Nuxt.js & Vue.js. Maintain the shared libraries for frontend engineers while working in the transaction tribes to migrate the old features into serverless architecture on AWS. Reduce the bundle size to increase overall performance by splitting into 3 repo based on the domain. Setup static sites development for the marketing team.',
    stacks: ['Nuxt.js', 'Vue.js', 'AWS'],
    layout: 'left',
    promotion: true,
  },
  {
    company: 'Blibli.com',
    link: 'https://www.blibli.com/',
    location: 'Jakarta, Indonesia',
    title: 'Sr. Software Development Engineer',
    period: 'Jan 2017 - Jun 2018',
    long: '1 yrs 6 mos',
    summary:
      'Built our very first digital products such as phone credits top ups, train ticket, flight ticket and hotel reservation. Transforming the frontend development process from SpringMVC in Java to Angular.js to Vue.js with under 10 team members.',
    stacks: ['Java', 'Angular.js', 'Vue.js', 'jQuery'],
    layout: 'right',
    promotion: false,
  },
  {
    company: 'Blibli.com',
    link: 'https://www.blibli.com/',
    location: 'Jakarta, Indonesia',
    title: 'Software Development Engineer',
    period: 'Oct 2015 - Jan 2017',
    long: '1 yrs 4 mos',
    summary:
      'Built our very first digital products such as phone credits top ups, train ticket, flight ticket and hotel reservation. Transforming the frontend development process from SpringMVC in Java to Angular.js to Vue.js with under 10 team members.',
    stacks: ['Java', 'Angular.js', 'Vue.js', 'jQuery'],
    layout: 'right',
    promotion: true,
  },
  {
    company: 'SML Technologies',
    link: 'https://smltech.co.id/',
    location: 'Jakarta, Indonesia',
    title: 'Java Developer',
    period: 'Aug 2013 -Oct 2015',
    long: '2 yrs 3 mos',
    summary:
      'Built our main product as desktop application using Java Swing and JIDE framework for client in telecom industry. Launch several monitoring dashboard using Sencha Ext.js and Fusion Chart.',
    stacks: ['Java', 'Ext.js', 'jQuery'],
    layout: 'left',
    promotion: false,
  },
];
