export const CAREERS = [
  {
    company: 'GovTech Edu',
    link: 'https://www.govtechedu.id/',
    location: 'Jakarta',
    title: '👩‍🏫 Software Development Engineer, Web',
    period: 'Jul 2023 - present',
    long: 'still counting',
  },
  {
    company: 'Sayurbox',
    link: 'https://www.sayurbox.com/',
    location: 'Jakarta',
    title: '🥦 Software Development Engineer III',
    period: 'Jul 2022 - May 2023',
    long: '11 months',
  },
  {
    company: 'Tokopedia',
    link: 'https://www.tokopedia.com/',
    location: 'Jakarta',
    title: '🦉 Principal Engineer Web Platform',
    period: 'Jun 2019 - Jul 2022',
    long: '3 yrs 2 mos',
  },
  {
    company: 'Bizzy Indonesia',
    link: 'https://bizzy.co.id/',
    location: 'Jakarta',
    title: '💼 Software Architect Frontend',
    period: 'Feb 2019 - Jun 2019',
    long: '5 mos',
  },
  {
    company: 'Bizzy Indonesia',
    link: 'https://bizzy.co.id/',
    location: 'Jakarta',
    title: '💼 Software Development Engineer',
    period: 'Jul 2018 - Feb 2019',
    long: '7 mos',
  },
  {
    company: 'Blibli.com',
    link: 'https://www.blibli.com/',
    location: 'Jakarta',
    title: '👜 Sr. Software Development Engineer',
    period: 'Jan 2017 - Jun 2018',
    long: '1 yrs 6 mos',
  },
  {
    company: 'Blibli.com',
    link: 'https://www.blibli.com/',
    location: 'Jakarta',
    title: '👜 Software Development Engineer',
    period: 'Oct 2015 - Jan 2017',
    long: '1 yrs 4 mos',
  },
  {
    company: 'SML Technologies',
    link: 'https://smltech.co.id/',
    location: 'Jakarta',
    title: '☕️ Java Developer',
    period: 'Aug 2013 -Oct 2015',
    long: '2 yrs 3 mos',
  },
];
