export const FEATURED_OSS = [
  {
    title: 'TanyaAja.in',
    desc: 'Platform to collect anonymous questions',
    repo: 'https://github.com/mazipan/tanyaaja',
    url: 'https://www.tanyaaja.in/',
    stacks: ['Firebase', 'Notion', 'Next.js', 'Shadcn UI', 'Tailwind CSS'],
  },
  {
    title: 'Ksana.in',
    desc: 'Simple URL shortener/beautifier for free',
    repo: 'https://github.com/mazipan/ksana.in',
    url: 'https://ksana.in/',
    stacks: ['Supabase', 'Next.js', 'Chakra-UI'],
  },
  {
    title: 'Learning.byphp.id',
    desc: 'An online learning list held by PHPID Community',
    repo: 'https://github.com/phpid-jakarta/phpid-learning',
    url: 'https://learning.byphp.id/',
    stacks: ['Svelte', 'Tailwind CSS'],
  },
  {
    title: 'Ajari Koding',
    desc: 'Curated learning resources by Indonesian Creator',
    repo: 'https://github.com/phpid-jakarta/ajari-koding',
    url: 'https://s.id/ajari-koding',
    stacks: ['Svelte', 'Bootstrap 5'],
  },
  {
    title: 'Baca-Quran.id',
    desc: "Web App to read The Holy Qur'an without Ads and Analytics",
    repo: 'https://github.com/mazipan/baca-quran.id',
    url: 'https://www.baca-quran.id/',
    stacks: ['Nuxt.js'],
  },
  {
    title: 'Pramuka.Online',
    desc: 'Currated learning materials around Indonesian Scout Activity (Pramuka)',
    repo: 'https://github.com/mazipan/pramuka.online',
    url: 'https://pramuka-id.vercel.app/',
    stacks: ['Next.js', 'Tailwind CSS'],
  },
  {
    title: 'PSI Github Actions',
    desc: 'Github Action to generate web performance report for JAMStack using PageSpeedInsight',
    repo: 'https://github.com/mazipan/psi-gh-action',
    url: 'https://github.com/marketplace/actions/psi-gh-action',
    stacks: ['Github Actions', 'PageSpeedInsight'],
  },
  {
    title: 'GraphQL PokeApi',
    desc: 'The GraphQL for PokeApi',
    repo: 'https://github.com/mazipan/graphql-pokeapi',
    url: 'https://graphql-pokeapi.vercel.app',
    stacks: ['GraphQl', 'Vercel'],
  },
  {
    title: 'E-commerce Web Perf',
    desc: 'Web Perf Comparison for E-Commerce in Indonesia ',
    repo: 'https://github.com/mazipan/webperf-ecommerce-id',
    url: 'https://webperf-ecommerce-id.vercel.app/',
    stacks: ['Next.js', 'PageSpeedInsight'],
  },
];
