import { Fragment, useState } from 'react'

import Meta from '@/components/Meta/Custom'
import LayoutArticle from '@/components/Layout/Default'

import DeviceChooser from '@/components/Speed/DeviceChooser'
import ScoreCard from '@/components/Speed/ScoreCard'

import { SITE_METADATA } from '@/lib/constants'
import { getPsiReportData } from '@/lib/api'

export default function Speed ({ data }) {
  const [showDevice, setShowDevice] = useState('all')

  const handleChangeDevice = (newDevice) => {
    setShowDevice(newDevice)
  }

  const newestData = data[0]
  const newestDataDesktop = newestData.reports.find((r) => r.device === 'desktop')
  const newestDataMobile = newestData.reports.find((r) => r.device === 'mobile')

  const allDataDesktop = data.map((d) => {
    const reports = d.reports.find((r) => r.device === 'desktop')
    return {
      ...d,
      ...reports,
      reports: undefined
    }
  })

  const allDataMobile = data.map((d) => {
    const reports = d.reports.find((r) => r.device === 'mobile')
    return {
      ...d,
      ...reports,
      reports: undefined
    }
  })

  return (
    <>
      <LayoutArticle>
        <Fragment>
          <Meta
            title="⚡️ Speed // mazipan.space"
            description="Web performance report of mazipan.space"
            url={`${SITE_METADATA.url}/speed`}
          />
          <h2 className="mb-8 text-6xl md:text-7xl font-heading font-bold tracking-tighter leading-tight">
            ⚡  Speed
          </h2>
          <div className="content">
            <div>
              Data generated by{' '}
              <a
                href="https://github.com/mazipan/psi-gh-action"
                target="_blank"
                rel="noreferrer"
                alt="psi-gh-action"
                className="border-dashed border-red-500 border-b-2 text-red-500"
              >
                psi-gh-action
              </a>
            </div>
            <span className="mb-4">
              🗓 &nbsp;&nbsp;Last Updated on {newestData.timestamp.substring(0, 10)}
            </span>

            <DeviceChooser activeDevice={showDevice} onChangeDevice={handleChangeDevice} />
            <ScoreCard activeDevice={showDevice} reportDesktop={newestDataDesktop} reportMobile={newestDataMobile} allDataDesktop={allDataDesktop} allDataMobile={allDataMobile} />
          </div>
        </Fragment>
      </LayoutArticle>
    </>
  )
}

export async function getStaticProps () {
  const data = getPsiReportData()

  return {
    props: {
      data
    }
  }
}
